import {
  IconSunFilled,
  IconMoonFilled,
  IconX,
  IconSearch,
  IconLoader2,
  IconStarFilled,
  IconBrandGithubFilled,
  IconBrandLinkedinFilled,
  IconWorldFilled,
  IconPhotoX,
  IconChevronLeft,
  IconUserCircle,
  IconCheck,
  IconShieldCheckFilled,
  IconSparklesFilled,
  IconMoodSad2,
} from "@tabler/icons-react";

const LightModeIcon = IconSunFilled,
  DarkModeIcon = IconMoonFilled,
  CloseIcon = IconX,
  SearchIcon = IconSearch,
  LoaderIcon = IconLoader2,
  RatingIcon = IconStarFilled,
  GithubIcon = IconBrandGithubFilled,
  LinkedinIcon = IconBrandLinkedinFilled,
  GlobeIcon = IconWorldFilled,
  ImageOffIcon = IconPhotoX,
  AccountIcon = IconUserCircle,
  CheckIcon = IconCheck,
  ShieldCheckIcon = IconShieldCheckFilled,
  SparkleIcon = IconSparklesFilled,
  SadIcon = IconMoodSad2,
  BackIcon = IconChevronLeft;

export {
  LightModeIcon,
  DarkModeIcon,
  CloseIcon,
  SearchIcon,
  LoaderIcon,
  RatingIcon,
  GithubIcon,
  LinkedinIcon,
  GlobeIcon,
  ImageOffIcon,
  BackIcon,
  AccountIcon,
  ShieldCheckIcon,
  CheckIcon,
  SparkleIcon,
  SadIcon,
};
